"""empty message

Revision ID: baeaca24069d
Revises: c2a21716aecf
Create Date: 2024-07-31 01:07:33.126260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baeaca24069d'
down_revision = 'c2a21716aecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('ad_description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('ad_terms', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('budget', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.drop_column('budget')
        batch_op.drop_column('ad_terms')
        batch_op.drop_column('ad_description')
        batch_op.drop_column('ad_name')

    # ### end Alembic commands ###
